
- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600
  sudo: true

- name: Install git
  apt: pkg=git-core state=present
  sudo: true

- name: Install wget package (Debian based)
  apt: pkg='wget' state=present
  only_if: "'$ansible_pkg_mgr' == 'apt'"
  sudo: true

- name: Install wget package (RedHat based)
  yum: name='wget' state=present
  only_if: "'$ansible_pkg_mgr' == 'yum'"
  sudo: true

- name: See if heroku is installed
  shell: "[ -f /usr/bin/heroku ] && echo 'Found' || echo ''"
  register: heroku_installed

- name: Install Heroku toolbelt
  shell: wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh
  when: (not heroku_installed.stdout)

- name: Map ssh-keys
  file: src=/vagrant/.ssh/$item dest=/home/${user}/.ssh/$item owner=${user} group=${user} state=link
  with_items:
    - id_rsa.pub
    - id_rsa

- name: Add Heroku keys
  shell: heroku keys:add < /vagrant/herokupw
  when: (not heroku_installed.stdout)
  
- name: Link bitstarter 
  file: src=/vagrant/bitstarter
        dest=/home/vagrant/bitstarter 
        owner=${user} group=${user} 
        state=link

