
- name: Install stuff needed to add apt-repository
  apt: pkg=$item state=present 
  with_items:
     - python-software-properties
     - python 
     - g++ 
     - make

- name: Add node.js apt-repository
  apt_repository: repo=ppa:webupd8team/java
  register: result

- name: apt-get update
  apt: update_cache=yes
  when_changed: $result

- name: Accept terms Oracle
  shell: sudo echo oracle-java7-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections
  sudo: true

- name: Add Oracle Java 7
  apt: pkg=oracle-java7-installer state=present
  register: oracle_java7_installed
  sudo: true

- name: Set Java 7 as default
  command: update-java-alternatives -s java-7-oracle
  when: oracle_java7_installed
  sudo: true

- name: Add Oracle Java 7 - defaults
  apt: pkg=oracle-java7-set-default state=present
  when: oracle_java7_installed
  sudo: true

- name: See if IntelliJ is installed
  shell: "[ -f /opt/intellij/idea-IC/bin/idea.sh ] && echo 'Found' || echo ''"
  register: intellij_installed

- name: Create directory for IntelliJ 
  file: path=/opt/intellij state=directory
  when: (not intellij_installed.stdout)
  sudo: true

- name: Download IntelliJ 
  command: wget http://download.jetbrains.com/idea/ideaIC-12.1.4.tar.gz
           creates=ideaIC-12.1.4.tar.gz
           chdir=/opt/intellij
  when: (not intellij_installed.stdout)
  sudo: true

- name: Install IntelliJ
  script: install_intellij.sh
  when: (not intellij_installed.stdout)
  sudo: true
  
- name: Link IntelliJ
  file: src=/opt/intellij/idea-IC/bin/idea.sh path=/usr/local/bin/idea.sh state=link
  sudo: true
